<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StatsEngineAPI.Domain\StatsEngineAPI.Domain.csproj" />
    <ProjectReference Include="..\StatsEngineAPI.Infrastructure\StatsEngineAPI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
